### ISSUE TITLE
Configure DNS server for Twingate connector in Helm values file

### ISSUE THREAD

**Issue by olwulff** [Twingate/helm-charts#27]
I'd like to be able to configure dns settings for the connector POD in Helm

i.e.
      dnsConfig:
        nameservers:
        - 192.168.1.55
      dnsPolicy: None

At the moment I had to manually update the deployment but I'd highly prefer to manage this via the helm values file.

**Comment by ekampf** [comment]
Hey @olwulff !
I'm wondering - whats your use case for using k8s's DNS policy vs. using the connectors `.Values. dnsServer` ?
