### ISSUE TITLE
Wrong data type in values.schema.json for image.tag

### ISSUE THREAD

**Issue by Punkoivan** [Twingate/helm-charts#33]
Hello folks,
with the latest chart update (connector-0.1.19.tgz) we had this error:
```
helm.go:84: [debug] values don't meet the specifications of the schema(s) in the following chart(s):
connector:
- image.tag: Invalid type. Expected: integer, given: string
```

Our values file is:
```
image:
  repository: "our.internal.repo"
  tag: "1.58.0"
```

Appears, that oneOf/anyOf doesn't work here:
https://github.com/Twingate/helm-charts/blob/master/stable/connector/values.schema.json#L20

Not sure if it's helm bug/feature, but the workaround is to update:
https://github.com/Twingate/helm-charts/blob/master/stable/connector/values.schema.json#L19

to:
```
 "type": "string",
```

If that suitable solution for you, I'll prepare PR.

Also, though it's another case, but please update you example's tag. In you docker hub repo you have zero tags as integer. All of them either string or float.

Thanks,
Ivan

**Comment by ekampf** [comment]
Hey @Punkoivan thanks for reporting!
I have opened a PR to fix this.

**Comment by Punkoivan** [comment]
Thanks!
TIL learned that "type" overriding "oneOf".
